### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [rbhughes/casaubon#1]
from here: https://github.com/rbhughes/casaubon/blob/1d610566c7946c45091b5a8b1c484811dcb20467/test_prom.js#L146

you shouldn't execute `commit` manually, it is done automatically by method `db.tx` that you are using.

**Comment by rbhughes** [comment]
Wow! Thanks for the tip, I'm shocked anyone noticed this obscure, fetal repo. The extra `commit` was necessary because of how the constraint's DEFERRED and DEFERRABLE get set at the beginning and unset at the end. If I remove the deferred constraints before the data is written, the constraints rightly fail. One alternative would be three calls: 1. define DEFERRED, 2. write data in transaction, 3. remove DEFERRED; do you have another suggestion?

**Comment by vitaly-t** [comment]
I'm not sure, if `DEFERRABLE` refers to the same... See [Configurable Transactions](https://github.com/vitaly-t/pg-promise#configurable-transactions)

**Comment by rbhughes** [comment]
The issue is now moot; here's the wrap-up:

My initial motivation was to preserve the database in its default state at all costs, and by default, no foreign keys were DEFERRABLE. This means that most of the time, I would have to wrap all this in a single transaction:

1. alter table/constraint to be DEFERRABLE
2. set the specific constraints to DEFERRED
3. insert whatever data would have violated the constraints to multiple tables
4. commit
5. alter table/constraints to be NOT DEFERRABLE (because that's how I found them)

In retrospect this was **bonkers**. The approach above does actually work for a single client, but adding more causes deadlocks. The golden rule: *it is madness to alter the schema in a transaction* --don't do it.

The sane solution is to set all the foreign key constraints to DEFERRABLE (INITIALLY IMMEDIATE) and just use a normal SET CONSTRAINTS ALL DEFERRED in the transaction.

**Comment by vitaly-t** [comment]
good to know ;)
